"""
Performance measurement & benchmarking logic (non-UI, no Streamlit
dependency).

This module measures how long BioVault's existing Phase 3-7 pipeline
functions (encoding, decoding, mutation, error correction, storage
analysis) actually take and how much memory they use *on the computer
running them right now*. It never invents or hardcodes a result -- every
number returned here comes from actually running the real pipeline
functions against deterministically generated test data.

IMPORTANT: these numbers are NOT portable performance claims. Execution
time and memory use depend on the host computer's hardware, current
system load, Python version, and the exact settings used (mutation
rate, block size, etc.). Every result this module produces should be
presented to the user labeled "Measured on this computer" -- never as a
universal benchmark.
"""

import time
import tracemalloc
from random import Random

from app.modules.dna_encoder import encode_file_to_dna
from app.modules.dna_decoder import decode_dna_to_file
from app.modules.dna_mutator import mutate_dna
from app.modules.dna_error_correction import (
    DEFAULT_BLOCK_SIZE,
    DEFAULT_REDUNDANCY_SIZE,
    add_redundancy,
    detect_errors,
    correct_substitution_errors,
)
from app.modules.storage_analysis import analyze_storage_efficiency

MEASUREMENT_LABEL = "Measured on this computer"

# Safe test-size presets (approximate; the generator produces the exact
# byte count requested). 1 MB is comfortably below file_handler.py's own
# MAX_FILE_SIZE_MB (5 MB) upload limit, so the "Large" preset reflects a
# realistic, safe upper bound rather than an artificial stress test that
# could freeze the Streamlit interface or use excessive memory.
SIZE_PRESETS = {
    "Small (~1 KB)": 1 * 1024,
    "Medium (~100 KB)": 100 * 1024,
    "Large (~1 MB)": 1 * 1024 * 1024,
}


class PerformanceAnalysisError(Exception):
    """Raised when performance-analysis inputs are invalid."""


def generate_deterministic_bytes(size_bytes: int, seed: int = 0) -> bytes:
    """Return `size_bytes` deterministically generated bytes.

    Using a fixed seed means the exact same test data is produced every
    time this is called with the same (size_bytes, seed) pair, on any
    machine -- so a performance test can be reproduced and compared
    across runs, even though the *timing* result will still vary by
    computer.
    """
    if isinstance(size_bytes, bool) or not isinstance(size_bytes, int) or size_bytes < 0:
        raise PerformanceAnalysisError("size_bytes must be a non-negative whole number.")

    return Random(seed).randbytes(size_bytes)


def measure_time(func, *args, **kwargs):
    """Run `func` once and return (result, elapsed_seconds).

    Uses time.perf_counter(), the standard-library high-resolution timer
    recommended for measuring short durations.
    """
    start = time.perf_counter()
    result = func(*args, **kwargs)
    elapsed_seconds = time.perf_counter() - start
    return result, elapsed_seconds


def measure_time_and_memory(func, *args, **kwargs):
    """Run `func` once and return (result, elapsed_seconds, peak_memory_bytes).

    Uses tracemalloc (Python standard library) to capture the peak
    additional memory allocated by Python objects while `func` runs.
    This is an approximation: it only tracks Python-level allocations
    tracemalloc can see, not the process's total OS-level memory (e.g.
    it won't see memory used by non-Python C extensions), and any other
    code running in the same interpreter at the same time would be
    included too. It is still useful as a relative "more data costs
    more memory" signal, which is all this page claims.
    """
    tracemalloc.start()
    try:
        start = time.perf_counter()
        result = func(*args, **kwargs)
        elapsed_seconds = time.perf_counter() - start
        _current, peak_memory_bytes = tracemalloc.get_traced_memory()
    finally:
        tracemalloc.stop()

    return result, elapsed_seconds, peak_memory_bytes


def run_encoding_benchmark(data: bytes) -> dict:
    """Time + measure memory for encoding `data` into a DNA sequence."""
    result, elapsed_seconds, peak_memory_bytes = measure_time_and_memory(encode_file_to_dna, data)
    return {
        "operation": "Encoding",
        "input_size_bytes": len(data),
        "output_dna_length": result["dna_length"],
        "elapsed_seconds": elapsed_seconds,
        "peak_memory_bytes": peak_memory_bytes,
        "note": MEASUREMENT_LABEL,
    }


def run_decoding_benchmark(dna_sequence: str) -> dict:
    """Time + measure memory for decoding `dna_sequence` back into bytes."""
    result, elapsed_seconds, peak_memory_bytes = measure_time_and_memory(decode_dna_to_file, dna_sequence)
    return {
        "operation": "Decoding",
        "input_dna_length": len(dna_sequence),
        "output_size_bytes": result["recovered_size_bytes"],
        "elapsed_seconds": elapsed_seconds,
        "peak_memory_bytes": peak_memory_bytes,
        "note": MEASUREMENT_LABEL,
    }


def run_mutation_benchmark(
    dna_sequence: str, mutation_type: str = "substitution", mutation_rate: float = 5.0, seed: int = 0
) -> dict:
    """Time + measure memory for one mutation pass over `dna_sequence`."""
    result, elapsed_seconds, peak_memory_bytes = measure_time_and_memory(
        mutate_dna, dna_sequence, mutation_type, mutation_rate, seed
    )
    return {
        "operation": "Mutation",
        "mutation_type": mutation_type,
        "mutation_rate": mutation_rate,
        "input_dna_length": len(dna_sequence),
        "output_dna_length": result["mutated_length"],
        "total_edits": result["total_edits"],
        "elapsed_seconds": elapsed_seconds,
        "peak_memory_bytes": peak_memory_bytes,
        "note": MEASUREMENT_LABEL,
    }


def run_error_correction_benchmark(
    dna_sequence: str, block_size: int = DEFAULT_BLOCK_SIZE, redundancy_size: int = DEFAULT_REDUNDANCY_SIZE
) -> dict:
    """Time + measure memory for a full add-redundancy -> detect -> correct
    pass over `dna_sequence` (no errors are introduced, so this measures
    the method's own overhead in isolation)."""

    def _full_pass():
        protection = add_redundancy(dna_sequence, block_size, redundancy_size)
        protected = protection["protected_sequence"]
        detect_errors(protected, block_size, redundancy_size, protection["original_length"])
        return correct_substitution_errors(protected, block_size, redundancy_size, protection["original_length"])

    result, elapsed_seconds, peak_memory_bytes = measure_time_and_memory(_full_pass)
    return {
        "operation": "Error Correction",
        "block_size": block_size,
        "redundancy_size": redundancy_size,
        "input_dna_length": len(dna_sequence),
        "protected_dna_length": len(result["received_sequence"]),
        "elapsed_seconds": elapsed_seconds,
        "peak_memory_bytes": peak_memory_bytes,
        "note": MEASUREMENT_LABEL,
    }


def run_storage_analysis_benchmark(file_size_bytes: int, dna_length: int) -> dict:
    """Time + measure memory for a storage-efficiency calculation.

    This calculation is simple arithmetic (no per-base loops), so it is
    expected to be extremely fast regardless of input size -- included
    for completeness so the comparison table covers every Phase 3-7
    calculation, not because it is expected to be a bottleneck.
    """
    result, elapsed_seconds, peak_memory_bytes = measure_time_and_memory(
        analyze_storage_efficiency, file_size_bytes, dna_length
    )
    return {
        "operation": "Storage Analysis",
        "input_size_bytes": file_size_bytes,
        "dna_length": dna_length,
        "raw_efficiency_percent": result["raw_efficiency_percent"],
        "elapsed_seconds": elapsed_seconds,
        "peak_memory_bytes": peak_memory_bytes,
        "note": MEASUREMENT_LABEL,
    }


def run_full_benchmark_suite(size_bytes: int, seed: int = 0) -> dict:
    """Run encoding, decoding, mutation, error correction, and storage
    analysis benchmarks over one deterministically generated test file,
    returning one structured dict the UI layer can display directly.
    """
    if isinstance(size_bytes, bool) or not isinstance(size_bytes, int) or size_bytes < 0:
        raise PerformanceAnalysisError("size_bytes must be a non-negative whole number.")

    test_data = generate_deterministic_bytes(size_bytes, seed)

    encoding = run_encoding_benchmark(test_data)
    dna_sequence = encode_file_to_dna(test_data)["dna_sequence"]
    # Decoding, mutation, and error correction all require a non-empty
    # DNA sequence (an empty sequence is a valid encoder output for an
    # empty file, but there is nothing for them to operate on) -- skip
    # them safely rather than letting their own validation raise.
    decoding = run_decoding_benchmark(dna_sequence) if dna_sequence else None
    mutation = run_mutation_benchmark(dna_sequence) if dna_sequence else None
    correction = run_error_correction_benchmark(dna_sequence) if dna_sequence else None
    storage = run_storage_analysis_benchmark(len(test_data), len(dna_sequence))

    total_elapsed_seconds = sum(
        entry["elapsed_seconds"]
        for entry in (encoding, decoding, mutation, correction, storage)
        if entry is not None
    )

    return {
        "input_size_bytes": size_bytes,
        "seed": seed,
        "encoding": encoding,
        "decoding": decoding,
        "mutation": mutation,
        "correction": correction,
        "storage": storage,
        "total_elapsed_seconds": total_elapsed_seconds,
        "note": MEASUREMENT_LABEL,
    }


def compare_size_presets(presets: dict = None, seed: int = 0) -> list:
    """Run the full benchmark suite for each preset size and return a
    list of results in the same order as `presets` (defaults to
    SIZE_PRESETS), suitable for a comparison table."""
    presets = presets if presets is not None else SIZE_PRESETS
    return [
        {"label": label, **run_full_benchmark_suite(size_bytes, seed)}
        for label, size_bytes in presets.items()
    ]
